# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62d7c82c8ec2019553feca6e1c256d690e48d72aafdf10579e5e35deb4cd930fe14d35e97b9328c4a25bdf5221dd9d63323ec4c10705184cbc4dae17b90a2108

test:
  secret_key_base: 0b1f7eb414497e28e684acce1cf08727bef4f4b7955e12b5fa947e30c2f482970a4928896ec6d18d0e4afe6c30798f5353ad8492d5ae3542c4fc73b4bdf74f31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
